### ISSUE TITLE
Missing method parameter?

### ISSUE THREAD

**Issue by neomafo88** [julKali/makeDebuggable#4]
https://github.com/julKali/makeDebuggable/blob/master/makeDebuggable.py#L210
`(strBytes, bytesRead2) = decodeLength(1)`

shouldn't it be `decodeLength(fs, 1)`?

**Comment by julKali** [comment]
yes, probably. have you encountered a bug or are you reviewing? if you want you can submit a PR, otherwise I'll try to fix it soon :)
